# Form implementation generated from reading ui file 'guiqt.ui'
#
# Created by: PyQt6 UI code generator 6.8.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(704, 374)
        font = QtGui.QFont()
        font.setFamily("Arial")
        MainWindow.setFont(font)
        MainWindow.setStyleSheet("background: black;")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(245, -30, 221, 91))
        font = QtGui.QFont()
        font.setFamily("Serati")
        font.setPointSize(36)
        font.setBold(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setStyleSheet("color: yellow;")
        self.label.setObjectName("label")
        self.startbtn = QtWidgets.QPushButton(parent=self.centralwidget)
        self.startbtn.setGeometry(QtCore.QRect(440, 290, 151, 50))
        font = QtGui.QFont()
        font.setFamily("Serati")
        font.setPointSize(24)
        self.startbtn.setFont(font)
        self.startbtn.setStyleSheet(".QPushButton{\n"
"color: yellow;\n"
"background:gray;\n"
"border-radius: 20px;\n"
"}\n"
".QPushButton:pressed{\n"
"color: #dea600;\n"
"background: #61605c;\n"
"}\n"
".QPushButton:hover{\n"
"color: orange;\n"
"}")
        self.startbtn.setObjectName("startbtn")
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(16, 40, 161, 91))
        font = QtGui.QFont()
        font.setFamily("Serati")
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: yellow;")
        self.label_2.setObjectName("label_2")
        self.imagesearch = QtWidgets.QPlainTextEdit(parent=self.centralwidget)
        self.imagesearch.setGeometry(QtCore.QRect(5, 100, 171, 51))
        self.imagesearch.setStyleSheet("background: gray;\n"
"color: Orange;\n"
"border-radius: 15px")
        self.imagesearch.setObjectName("imagesearch")
        self.label_3 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(490, 40, 201, 91))
        font = QtGui.QFont()
        font.setFamily("Serati")
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color: yellow;")
        self.label_3.setObjectName("label_3")
        self.match_text = QtWidgets.QPlainTextEdit(parent=self.centralwidget)
        self.match_text.setGeometry(QtCore.QRect(510, 99, 161, 51))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        self.match_text.setFont(font)
        self.match_text.setStyleSheet("background: gray;\n"
"color: Orange;\n"
"border-radius: 15px;\n"
"")
        self.match_text.setObjectName("match_text")
        self.infobtn = QtWidgets.QPushButton(parent=self.centralwidget)
        self.infobtn.setGeometry(QtCore.QRect(630, 350, 75, 23))
        self.infobtn.setStyleSheet("color: orange;\n"
"background: 43, 43, 43;")
        self.infobtn.setObjectName("infobtn")
        self.interval = QtWidgets.QPlainTextEdit(parent=self.centralwidget)
        self.interval.setGeometry(QtCore.QRect(259, 98, 171, 51))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        self.interval.setFont(font)
        self.interval.setStyleSheet("background: gray;\n"
"color: Orange;\n"
"border-radius: 15px")
        self.interval.setObjectName("interval")
        self.label_4 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(300, 64, 91, 41))
        font = QtGui.QFont()
        font.setFamily("Serati")
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color: yellow;")
        self.label_4.setObjectName("label_4")
        self.interval_pause = QtWidgets.QPlainTextEdit(parent=self.centralwidget)
        self.interval_pause.setGeometry(QtCore.QRect(1, 179, 171, 51))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        self.interval_pause.setFont(font)
        self.interval_pause.setStyleSheet("background: gray;\n"
"color: Orange;\n"
"border-radius: 15px")
        self.interval_pause.setObjectName("interval_pause")
        self.label_5 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(7, 146, 171, 41))
        font = QtGui.QFont()
        font.setFamily("Serati")
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("color: yellow;")
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(237, 180, 111, 61))
        font = QtGui.QFont()
        font.setFamily("Serati")
        font.setPointSize(24)
        font.setBold(False)
        font.setWeight(50)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("color: yellow;")
        self.label_6.setObjectName("label_6")
        self.active = QtWidgets.QLabel(parent=self.centralwidget)
        self.active.setGeometry(QtCore.QRect(352, 180, 111, 61))
        font = QtGui.QFont()
        font.setFamily("Serati")
        font.setPointSize(24)
        font.setBold(False)
        font.setWeight(50)
        self.active.setFont(font)
        self.active.setStyleSheet("color: red;")
        self.active.setObjectName("active")
        self.stopbtn = QtWidgets.QPushButton(parent=self.centralwidget)
        self.stopbtn.setGeometry(QtCore.QRect(90, 290, 151, 50))
        font = QtGui.QFont()
        font.setFamily("Serati")
        font.setPointSize(24)
        self.stopbtn.setFont(font)
        self.stopbtn.setStyleSheet(".QPushButton{\n"
"color: yellow;\n"
"background:gray;\n"
"border-radius: 20px;\n"
"}\n"
".QPushButton:pressed{\n"
"color: #dea600;\n"
"background: #61605c;\n"
"}\n"
".QPushButton:hover{\n"
"color: orange;\n"
"}")
        self.stopbtn.setObjectName("stopbtn")
        self.label_5.raise_()
        self.label_4.raise_()
        self.label.raise_()
        self.startbtn.raise_()
        self.label_2.raise_()
        self.imagesearch.raise_()
        self.label_3.raise_()
        self.match_text.raise_()
        self.infobtn.raise_()
        self.interval.raise_()
        self.interval_pause.raise_()
        self.label_6.raise_()
        self.active.raise_()
        self.stopbtn.raise_()
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "AutoSkip tg: @dishacker"))
        self.label.setText(_translate("MainWindow", "AutoSkip"))
        self.startbtn.setText(_translate("MainWindow", "START"))
        self.label_2.setText(_translate("MainWindow", "Image search"))
        self.imagesearch.setPlainText(_translate("MainWindow", "image/file.png\n"
"image/file2.png"))
        self.label_3.setText(_translate("MainWindow", "match percentage"))
        self.match_text.setPlainText(_translate("MainWindow", "90"))
        self.infobtn.setText(_translate("MainWindow", "info"))
        self.interval.setPlainText(_translate("MainWindow", "3"))
        self.label_4.setText(_translate("MainWindow", "interval"))
        self.interval_pause.setPlainText(_translate("MainWindow", "180"))
        self.label_5.setText(_translate("MainWindow", "interval pause"))
        self.label_6.setText(_translate("MainWindow", "active: "))
        self.active.setText(_translate("MainWindow", "OFF"))
        self.stopbtn.setText(_translate("MainWindow", "STOP"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
